services:
  airsdk:
    platform: linux/amd64
    image: airsdk:${SDK_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SDK_VERSION: ${SDK_VERSION}
        SDK_ARCHIVE: ${SDK_ARCHIVE}
